import type { Metadata } from 'next'
import { Onest } from 'next/font/google'
import '@/styles/globals.css'
import Header from '@/components/shared/header'

const onestSans = Onest({
	variable: '--font-onest',
	subsets: ['latin']
})

export const metadata: Metadata = {	
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body className={`${onestSans.variable} antialiased min-h-screen flex flex-col`}>
				<Header />
				<main className='flex-1'>{children}</main>
				<footer className='container'>footer</footer>
			</body>
		</html>
	)
}
